<?php
include('include/config.php');
include('include/header.php');
 ?>
<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <span><h1 class="page-header">KB <span class="pull-right">

                                    <select id="status_filter" class="form-control" onchange="window.location.href='?status='+this.value">
                                        <?php $sxx=mysqli_query($conn,"SELECT * FROM  status_role ORDER BY kb_id DESC ");
                                        while($an=mysqli_fetch_assoc($sxx)) {
                                            ?>
                                            <option value="<?=$an['kb_id']?>"><?=$an['status_name']?></option>

                                            <?php
                                        }
                                        ?>
                                    </select>

                                </span></h1></span>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row table-responsive table-bordered">
                <table class="table">
                    <strong><tr style="background-color:rgba(112, 255, 173, 0.52); font-weight: 700;"><td>KB Name</td>
                        <td>Status</td>
                        <td>Generated Date</td>
                        <td>Generated By</td>
                        <td>Assigned Developer</td>
                        <td>Assigned Tester</td>
                        <td>Due Date</td>
                        <td>Priority</td>
                    </tr></strong>

                <?php
                $sx="";
                   if(isset($_GET['status'])&&$_GET['status']!='11'){
                       $sx=mysqli_query($conn,"SELECT * FROM  kb k inner JOIN status_role s ON k.kb_status=s.kb_id WHERE kb_status='".$_GET['status']."' ORDER BY k.kb_id");
                       ?>
                       <script>
                          // $('#status_filter').val();
                           document.getElementById('status_filter').value=<?=$_GET['status']?>;

                       </script>
                       <?php
                   }else{
                       $sx=mysqli_query($conn,"SELECT * FROM  kb k inner JOIN status_role s ON k.kb_status=s.kb_id ORDER BY k.kb_id") or die($conn->error);
                   }

                    while($ans=mysqli_fetch_assoc($sx))
                    {
                      ?>

                     <tr>
                      <td>  [<?=$ans['kb_id']?>]:<b><?=$ans['kb_name']?></b></td>
                       <td>
                       <?=$ans['status_name']?>
                       </td>
                       <td> <?=$ans['kb_gen_date']?></td>
                         <td> <?=$ans['kb_gen_by']?></td>
                         <td> <?=$ans['kb_assign_dev']?></td>
                         <td> <?=$ans['kb_assign_tester']?></td>
                         <td> <?=$ans['kb_due_date']?></td>
                         <td> <?=$ans['kb_priorty']?></td>
                     </tr>
                        <tr style="border-top: 0; border-top-color: transparent;">
                            <td style="border-top: 0; border-top-color: transparent;" colspan="7"> <?=$ans['title']?></td>
                            <td style="border-top: 0; border-top-color: transparent;" colspan="1        "><button class="btn btn-sm btn-danger">Edit</button></td>
                        </tr>
                      <?php
                    }
                 ?>
                </table>
            </div>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
<?php
include('include/footer.php');
?>
